import { describe, expect, it } from 'vitest';
import { MeetingPolicyError, meetingPolicySettings, resolveMeetingPolicy, type MeetingPolicyInput } from './policy';
function input(): MeetingPolicyInput {
 return { scope: { tenantId: 'tenant1', userId: 'user1', groupIds: [] },
  tenant: { tenantId: 'tenant1', settings: Object.fromEntries(meetingPolicySettings.map(k => [k, { value: k === 'waitingRoom' }])) as MeetingPolicyInput['tenant']['settings'] }, groups: [] };
}
function group(data: MeetingPolicyInput, groupId: string, settings: MeetingPolicyInput['groups'][number]['settings']) {
 data.scope.groupIds.push(groupId); data.groups.push({ tenantId: data.scope.tenantId, groupId, settings });
}
function code(data: unknown, expected: MeetingPolicyError['code']) {
 try {resolveMeetingPolicy(data);throw new Error('Expected rejection');} catch(error){expect(error).toBeInstanceOf(MeetingPolicyError);expect((error as MeetingPolicyError).code).toBe(expected);}
}
describe('meeting policy resolution',()=>{
 it('returns explicit tenant defaults with provenance',()=>{const result=resolveMeetingPolicy(input());expect(result.settings.publishAudio).toEqual({value:false,source:{level:'tenant',id:'tenant1'},locked:false});expect(result.settings.waitingRoom.value).toBe(true);});
 it('uses explicit ordered group defaults, then user, then meeting',()=>{const data=input();group(data,'a',{publishAudio:{value:true}});group(data,'b',{publishAudio:{value:false}});expect(resolveMeetingPolicy(data).settings.publishAudio.source.id).toBe('b');data.user={tenantId:'tenant1',userId:'user1',settings:{publishAudio:true}};expect(resolveMeetingPolicy(data).settings.publishAudio.value).toBe(true);data.scope.meetingId='meeting1';data.meeting={tenantId:'tenant1',meetingId:'meeting1',settings:{publishAudio:false}};expect(resolveMeetingPolicy(data).settings.publishAudio).toMatchObject({value:false,source:{level:'meeting',id:'meeting1'}});});
 it('preserves tenant lock over conflicting unlocked group defaults',()=>{const data=input();data.tenant.settings.waitingRoom.locked=true;group(data,'a',{waitingRoom:{value:false}});expect(resolveMeetingPolicy(data).settings.waitingRoom).toEqual({value:true,source:{level:'tenant',id:'tenant1'},locked:true,lockReason:'Locked by tenant tenant1'});});
 it('a group lock wins over unlocked defaults in either order',()=>{const data=input();group(data,'a',{publishVideo:{value:false,locked:true}});group(data,'b',{publishVideo:{value:true}});for(const groups of [data.groups,[...data.groups].reverse()])expect(resolveMeetingPolicy({...data,groups}).settings.publishVideo).toMatchObject({value:false,locked:true,source:{id:'a'}});});
 it('rejects conflicting group locks independent of order',()=>{const data=input();group(data,'a',{recordingAllowed:{value:true,locked:true}});group(data,'b',{recordingAllowed:{value:false,locked:true}});code(data,'POLICY_CONFLICT');code({...data,groups:[...data.groups].reverse()},'POLICY_CONFLICT');});
 it('chooses deterministic source for equal group locks',()=>{const data=input();group(data,'b',{publishScreen:{value:false,locked:true}});group(data,'a',{publishScreen:{value:false,locked:true}});expect(resolveMeetingPolicy(data).settings.publishScreen.source.id).toBe('a');});
 it('rejects contradictory tenant/group locks',()=>{const data=input();data.tenant.settings.interpreterAllowed.locked=true;group(data,'a',{interpreterAllowed:{value:true,locked:true}});code(data,'POLICY_CONFLICT');});
 it.each(meetingPolicySettings)('locks %s in either boolean direction',key=>{for(const value of [true,false]){const data=input();data.tenant.settings[key]={value,locked:true};data.user={tenantId:'tenant1',userId:'user1',settings:{[key]:!value}};code(data,'POLICY_LOCKED');data.user.settings[key]=value;expect(resolveMeetingPolicy(data).settings[key]).toMatchObject({value,source:{level:'tenant'},locked:true});}});
 it('meeting cannot override group lock through identical user value',()=>{const data=input();group(data,'a',{guestAccess:{value:false,locked:true}});data.user={tenantId:'tenant1',userId:'user1',settings:{guestAccess:false}};data.scope.meetingId='m1';data.meeting={tenantId:'tenant1',meetingId:'m1',settings:{guestAccess:true}};code(data,'POLICY_LOCKED');});
 it('does not mutate input or share output state with input',()=>{const data=input(),before=JSON.stringify(data),result=resolveMeetingPolicy(data);result.settings.guestAccess.value=true;expect(JSON.stringify(data)).toBe(before);expect(resolveMeetingPolicy(data).settings.guestAccess.value).toBe(false);});
});
describe('runtime and tenant boundaries',()=>{
 it('rejects cross-tenant policy at every layer',()=>{for(const layer of ['tenant','group','user','meeting']){const data=input();if(layer==='tenant')data.tenant.tenantId='other';if(layer==='group'){group(data,'a',{});data.groups[0].tenantId='other';}if(layer==='user')data.user={tenantId:'other',userId:'user1',settings:{}};if(layer==='meeting'){data.scope.meetingId='m1';data.meeting={tenantId:'other',meetingId:'m1',settings:{}};}code(data,'POLICY_SCOPE');}});
 it('rejects wrong user or meeting identity',()=>{const data=input();data.user={tenantId:'tenant1',userId:'other',settings:{}};code(data,'POLICY_SCOPE');delete data.user;data.scope.meetingId='m1';data.meeting={tenantId:'tenant1',meetingId:'m2',settings:{}};code(data,'POLICY_SCOPE');});
 it('rejects missing, extra, duplicate or unassigned group records',()=>{const data=input();group(data,'a',{});for(const candidate of [{...data,groups:[]},{...data,groups:[...data.groups,...data.groups]},{...data,scope:{...data.scope,groupIds:[]}},{...data,scope:{...data.scope,groupIds:['a','a']}}])code(candidate,'POLICY_SCOPE');});
 it('requires meeting policy record when resolving a meeting scope',()=>{const data=input();data.scope.meetingId='m1';code(data,'POLICY_SCOPE');});
 it('rejects unknown settings, coercion and malformed records',()=>{for(const candidate of [null,{}, {...input(),extra:true},{...input(),tenant:{tenantId:'tenant1',settings:{}}},{...input(),tenant:{tenantId:'tenant1',settings:{...input().tenant.settings,guestAccess:{value:'false'}}}},{...input(),tenant:{tenantId:'tenant1',settings:{...input().tenant.settings,unlisted:{value:true}}}},{...input(),user:{tenantId:'tenant1',userId:'user1',settings:{guestAccess:{value:true,locked:true}}}}])code(candidate,'INVALID_POLICY');});
});
