import { createServer, type Socket } from 'node:net';
import { describe,it,expect } from 'vitest';
import { EslFrames,createEslCaptureTransport } from '../server/cloud-recordings/esl-capture';
const id='11111111-1111-4111-8111-111111111111',peer='22222222-2222-4222-8222-222222222222';
const announcement='/opt/phone11ai/prompts/recording.wav';
function frame(s:Socket,type:string,body:string){s.write(`Content-Type: ${type}\nContent-Length: ${Buffer.byteLength(body)}\n\n${body}`);}
async function fixture(fn:(command:string,s:Socket)=>void){const sockets=new Set<Socket>();const server=createServer(s=>{sockets.add(s);s.on('close',()=>sockets.delete(s));s.write('Content-Type: auth/request\n\n');let pending='';s.on('data',d=>{pending+=d.toString();let at;while((at=pending.indexOf('\n\n'))>=0){const c=pending.slice(0,at);pending=pending.slice(at+2);if(c==='auth fixture')s.write('Content-Type: command/reply\nReply-Text: +OK accepted\n\n');else fn(c,s);}});});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));return {port:(server.address()as any).port,close:async()=>{for(const s of sockets)s.destroy();await new Promise<void>(r=>server.close(()=>r()));}};}
describe('authenticated recording ESL',()=>{
 it('parses fragmented frames and rejects oversized input',()=>{const p=new EslFrames();expect(p.push(Buffer.from('Content-Length: 3\n\nx'))).toEqual([]);expect(p.push(Buffer.from('yz'))[0].body).toBe('xyz');expect(()=>p.push(Buffer.alloc(1024*1024+1))).toThrow();});
 it('executes a bounded authenticated command on actual local TCP',async()=>{const f=await fixture((c,s)=>{expect(c).toBe('api uuid_exists '+id);frame(s,'api/response','+OK');});try{const t=createEslCaptureTransport({host:'127.0.0.1',port:f.port,password:'fixture',announcementPath:announcement});expect(await t.api('uuid_exists '+id)).toBe('+OK');}finally{await f.close();}});
 it('rejects interrupted announcement and requires command acceptance after early events',async()=>{for(const bad of ['break','missing','rejected']){const f=await fixture((c,s)=>{if(c==='event json PLAYBACK_STOP')s.write('Content-Type: command/reply\nReply-Text: +OK\n\n');else if(c.startsWith('api uuid_getvar'))frame(s,'api/response',peer);else{for(const channel of [id,peer])frame(s,'text/event-json',JSON.stringify({'Event-Name':'PLAYBACK_STOP','Unique-ID':channel,'Playback-File-Path':announcement,...(bad==='missing'?{}:{'Playback-Status':bad==='break'?'break':'done'})}));frame(s,'api/response','-ERR rejected');}});try{await expect(createEslCaptureTransport({host:'127.0.0.1',port:f.port,password:'fixture',announcementPath:announcement}).announceBoth({channelUuid:id,callUuid:'call',tenantId:1,extensionId:1,token:'t',path:'/var/lib/freeswitch/recordings/phone11/1/t.wav'})).rejects.toThrow();}finally{await f.close();}}});
 it('subscribes before stop and waits for exact completed recording',async()=>{let subscribed=false;const file=`/var/lib/freeswitch/recordings/phone11/1/${peer}.wav`;const f=await fixture((c,s)=>{if(c==='event json RECORD_STOP'){subscribed=true;s.write('Content-Type: command/reply\nReply-Text: +OK\n\n');}else{expect(subscribed).toBe(true);frame(s,'api/response','+OK');frame(s,'text/event-json',JSON.stringify({'Event-Name':'RECORD_STOP','Unique-ID':id,'Record-File-Path':file}));}});try{expect(await createEslCaptureTransport({host:'127.0.0.1',port:f.port,password:'fixture',announcementPath:announcement}).api(`uuid_record ${id} stop ${file}`)).toBe('+OK recording stopped');}finally{await f.close();}});
 it('waits for both exact playback completions, not enqueue ACK',async()=>{const f=await fixture((c,s)=>{if(c==='event json PLAYBACK_STOP')s.write('Content-Type: command/reply\nReply-Text: +OK\n\n');else if(c.startsWith('api uuid_getvar'))frame(s,'api/response',peer);else{frame(s,'api/response','+OK');for(const channel of [id,peer])frame(s,'text/event-json',JSON.stringify({'Event-Name':'PLAYBACK_STOP','Unique-ID':channel,'Playback-File-Path':announcement,'Playback-Status':'done'}));}});try{await createEslCaptureTransport({host:'127.0.0.1',port:f.port,password:'fixture',announcementPath:announcement}).announceBoth({channelUuid:id,callUuid:'call',tenantId:1,extensionId:1,token:'t',path:'/var/lib/freeswitch/recordings/phone11/1/t.wav'});}finally{await f.close();}});
});
