import {describe,it,expect,vi} from 'vitest';
import {createChatNotificationCoordinator,type NotificationIdentity} from '../lib/notifications/coordinator';
const eventId='00000000-0000-4000-8000-000000000001';
const event={type:'phone11_chat',eventId};
function deferred<T>() {let resolve!:(v:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return {promise,resolve};}
function fixture() {
 let identity:NotificationIdentity={owner:{},tenantId:10,active:true,enabled:true};
 const deps={identity:()=>identity,permission:vi.fn(async(_request:boolean)=>true),token:vi.fn(async()=>'a'.repeat(64)),register:vi.fn(async(_token:string,_tenant:number,_current:()=>boolean)=>true),resolve:vi.fn(async()=>({tenantId:10,conversationId:eventId})),open:vi.fn(),unavailable:vi.fn()};
 return {deps,c:createChatNotificationCoordinator(deps),set:(change:Partial<NotificationIdentity>)=>{identity={...identity,...change};}};
}
describe('ordinary chat notification identity and tap lifecycle',()=>{
 it('default disabled does no permission, token, registration or resolution work',async()=>{const f=fixture();f.set({enabled:false});await f.c.refresh(true);await f.c.tap(event);expect(f.deps.permission).not.toHaveBeenCalled();expect(f.deps.token).not.toHaveBeenCalled();expect(f.deps.resolve).not.toHaveBeenCalled();});
 it('requests permission only through explicit action and never enrolls when denied',async()=>{const f=fixture();f.deps.permission.mockResolvedValue(false);await f.c.refresh();expect(f.deps.permission).toHaveBeenLastCalledWith(false);await f.c.refresh(true);expect(f.deps.permission).toHaveBeenLastCalledWith(true);expect(f.deps.register).not.toHaveBeenCalled();});
 it.each(['owner','tenantId','active'] as const)('late native token cannot bind replacement %s',async key=>{const f=fixture(),d=deferred<string>();f.deps.token.mockReturnValue(d.promise);const work=f.c.refresh();await Promise.resolve();f.set(key==='owner'?{owner:{}}:key==='tenantId'?{tenantId:20}:{active:false});d.resolve('b'.repeat(64));await work;expect(f.deps.register).not.toHaveBeenCalled();});
 it('coalesces registration while native permission/token work is pending',async()=>{const f=fixture(),d=deferred<boolean>();f.deps.permission.mockReturnValue(d.promise);const one=f.c.refresh(),two=f.c.refresh();d.resolve(true);await Promise.all([one,two]);expect(f.deps.register).toHaveBeenCalledOnce();});
 it('resolves opaque event on server before opening and ignores payload route fields',async()=>{const f=fixture();await f.c.tap({...event,tenantId:999,conversationId:'attacker',body:'secret'});expect(f.deps.resolve).toHaveBeenCalledWith(eventId,expect.any(Function));expect(f.deps.open).toHaveBeenCalledWith({tenantId:10,conversationId:eventId});});
 it('deduplicates simultaneous and repeated callbacks',async()=>{const f=fixture(),d=deferred<any>();f.deps.resolve.mockReturnValue(d.promise);const first=f.c.tap(event);await f.c.tap(event);d.resolve({tenantId:10,conversationId:eventId});await first;await f.c.tap(event);expect(f.deps.resolve).toHaveBeenCalledOnce();expect(f.deps.open).toHaveBeenCalledOnce();});
 it('queues cold-start tap through auth hydration',async()=>{const f=fixture();f.set({owner:null,enabled:false});await f.c.tap(event);f.set({owner:{},enabled:true});f.c.invalidate();await f.c.resumeTap();expect(f.deps.open).toHaveBeenCalledOnce();});
 it('queues inactive tap until foreground and revalidates it',async()=>{const f=fixture();f.set({active:false});await f.c.tap(event);expect(f.deps.resolve).not.toHaveBeenCalled();f.set({active:true});f.c.invalidate();await f.c.resumeTap();expect(f.deps.open).toHaveBeenCalledOnce();});
 it('old resolution cannot navigate a replacement owner or workspace',async()=>{const f=fixture(),d=deferred<any>();f.deps.resolve.mockReturnValue(d.promise);const work=f.c.tap(event);f.set({owner:{},tenantId:20});f.c.invalidate(true);d.resolve({tenantId:10,conversationId:eventId});await work;await f.c.resumeTap();expect(f.deps.open).not.toHaveBeenCalled();});
 it('revoked or expired event shows only generic unavailable guidance',async()=>{const f=fixture();f.deps.resolve.mockResolvedValue(null as any);await f.c.tap(event);expect(f.deps.open).not.toHaveBeenCalled();expect(f.deps.unavailable).toHaveBeenCalledOnce();});
 it('unmount invalidates pending token and event work',async()=>{const f=fixture(),d=deferred<any>();f.deps.resolve.mockReturnValue(d.promise);const work=f.c.tap(event);f.c.stop();d.resolve({tenantId:10,conversationId:eventId});await work;expect(f.deps.open).not.toHaveBeenCalled();});
});

it('a newer tap wins while an earlier event is resolving',async()=>{const f=fixture(),d=deferred<any>();f.deps.resolve.mockReturnValueOnce(d.promise);const a=f.c.tap(event);const second='00000000-0000-4000-8000-000000000002';await f.c.tap({...event,eventId:second});d.resolve({tenantId:10,conversationId:'old'});await a;expect(f.deps.resolve).toHaveBeenCalledTimes(2);expect(f.deps.open).toHaveBeenCalledOnce();expect(f.deps.open).not.toHaveBeenCalledWith({tenantId:10,conversationId:'old'});});

it('failed earlier tap preserves and drains a newer event',async()=>{const f=fixture();let reject!:(e:Error)=>void;f.deps.resolve.mockReturnValueOnce(new Promise((_,r)=>{reject=r;}));const a=f.c.tap(event);await f.c.tap({...event,eventId:'00000000-0000-4000-8000-000000000002'});reject(new Error('private'));await a;expect(f.deps.open).toHaveBeenCalledOnce();expect(f.deps.unavailable).not.toHaveBeenCalled();});
it('permission action returns success only for actual current enrollment',async()=>{const f=fixture();expect(await f.c.refresh(true)).toEqual({status:'enabled'});f.deps.register.mockResolvedValue(false);expect(await f.c.refresh(true)).toEqual({status:'unavailable'});f.deps.permission.mockResolvedValue(false);expect(await f.c.refresh(true)).toEqual({status:'permission-denied'});});

it('explicit enable waits for passive work then requests permission rather than losing the prompt',async()=>{const f=fixture(),d=deferred<boolean>();f.deps.permission.mockReturnValueOnce(d.promise).mockResolvedValueOnce(true);const passive=f.c.refresh();const action=f.c.refresh(true);d.resolve(false);expect(await passive).toEqual({status:'permission-denied'});expect(await action).toEqual({status:'enabled'});expect(f.deps.permission.mock.calls.map(c=>c[0])).toEqual([false,true]);expect(f.deps.register).toHaveBeenCalledOnce();});

it('post-permission enrollment times out and late native token cannot bind',async()=>{vi.useFakeTimers();try{const f=fixture(),d=deferred<string>();f.deps.token.mockReturnValue(d.promise);const work=f.c.refresh(true);await vi.advanceTimersByTimeAsync(15_001);expect(await work).toEqual({status:'unavailable'});d.resolve('b'.repeat(64));await Promise.resolve();await Promise.resolve();expect(f.deps.register).not.toHaveBeenCalled();}finally{vi.useRealTimers();}});
it('late server registration completion cannot turn timeout into success',async()=>{vi.useFakeTimers();try{const f=fixture(),d=deferred<boolean>();f.deps.register.mockReturnValue(d.promise);const work=f.c.refresh(true);await vi.advanceTimersByTimeAsync(15_001);expect(await work).toEqual({status:'unavailable'});const guard=f.deps.register.mock.calls[0]?.[2] as undefined|(()=>boolean);if(guard)expect(guard()).toBe(false);d.resolve(true);await Promise.resolve();}finally{vi.useRealTimers();}});

it('legitimate iOS permission inactive/active cycle preserves explicit enable completion',async()=>{vi.useFakeTimers();try{const f=fixture(),d=deferred<boolean>();f.deps.permission.mockReturnValue(d.promise);const action=f.c.refresh(true);f.set({active:false});f.c.invalidate(false,true);d.resolve(true);await Promise.resolve();f.set({active:true});f.c.invalidate(false,true);await vi.advanceTimersByTimeAsync(51);expect(await action).toEqual({status:'enabled'});expect(f.deps.register).toHaveBeenCalledOnce();}finally{vi.useRealTimers();}});
it('permission grant after workspace change cannot enable the replacement workspace',async()=>{const f=fixture(),d=deferred<boolean>();f.deps.permission.mockReturnValue(d.promise);const action=f.c.refresh(true);f.set({tenantId:20});f.c.invalidate();d.resolve(true);expect(await action).toEqual({status:'session-changed'});expect(f.deps.register).not.toHaveBeenCalled();});
