import { promises as fs } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe,it,expect,vi } from 'vitest';
import { createCaptureSpool } from '../server/cloud-recordings/capture-spool';
const lease={channelUuid:'11111111-1111-4111-8111-111111111111',callUuid:'call',tenantId:2,extensionId:3,token:'22222222-2222-4222-8222-222222222222',path:'/var/lib/freeswitch/recordings/phone11/2/22222222-2222-4222-8222-222222222222.wav'};
describe('durable completed-recording spool',()=>{
 it('retries durable bytes with exact call/tenant/token and authenticated HTTPS',async()=>{const directory=await fs.mkdtemp(join(tmpdir(),'capture-spool-'));await fs.chmod(directory,0o700);const wav=Buffer.alloc(44);wav.write('RIFF');wav.write('WAVE',8);wav.writeUInt32LE(36,4);await fs.writeFile(join(directory,'22222222-2222-4222-8222-222222222222.wav'),wav,{mode:0o600});const upload=vi.fn().mockResolvedValueOnce(new Response('',{status:503})).mockResolvedValueOnce(Response.json({ok:true,storageKey:'stored'}));try{const spool=createCaptureSpool({directory,endpoint:'https://example.invalid/api/recordings/upload',integrationSecret:'fixture',fetch:upload});await expect(spool.putCompleted(lease)).rejects.toThrow();expect(await spool.putCompleted(lease)).toBe('stored');const [url,options]=upload.mock.calls[1];expect(url.searchParams.get('capture_token')).toBe('22222222-2222-4222-8222-222222222222');expect(url.searchParams.get('tenant_id')).toBe('2');expect(options.redirect).toBe('error');expect([...options.body].every((v:number)=>v===0)).toBe(true);expect(await fs.readFile(join(directory,'22222222-2222-4222-8222-222222222222.wav'))).toEqual(wav);}finally{await fs.rm(directory,{recursive:true});}});
 it('rejects crash-truncated final WAV before network',async()=>{const directory=await fs.mkdtemp(join(tmpdir(),'capture-spool-'));await fs.chmod(directory,0o700);const wav=Buffer.alloc(44);wav.write('RIFF');wav.write('WAVE',8);wav.writeUInt32LE(4096,4);await fs.writeFile(join(directory,lease.token+'.wav'),wav);const upload=vi.fn();try{await expect(createCaptureSpool({directory,endpoint:'https://example.invalid/api/recordings/upload',integrationSecret:'fixture',fetch:upload}).putCompleted(lease)).rejects.toThrow();expect(upload).not.toHaveBeenCalled();}finally{await fs.rm(directory,{recursive:true});}});
 it('rejects symlinked spool audio before network',async()=>{const directory=await fs.mkdtemp(join(tmpdir(),'capture-spool-'));await fs.chmod(directory,0o700);await fs.symlink('/etc/passwd',join(directory,'22222222-2222-4222-8222-222222222222.wav'));const upload=vi.fn();try{await expect(createCaptureSpool({directory,endpoint:'https://example.invalid/api/recordings/upload',integrationSecret:'fixture',fetch:upload}).putCompleted(lease)).rejects.toThrow();expect(upload).not.toHaveBeenCalled();}finally{await fs.rm(directory,{recursive:true});}});
});
