import { randomBytes } from "node:crypto";
import { readFile } from "node:fs/promises";
import { URL } from "node:url";
import { Pool, type PoolClient } from "pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

const connectionString = process.env.PHONE11_PBX_TEST_DATABASE_URL;
if (connectionString) {
  const url = new URL(connectionString);
  if (!["postgres:", "postgresql:"].includes(url.protocol) ||
      !["127.0.0.1", "localhost", "[::1]"].includes(url.hostname) ||
      url.pathname !== "/phone11_pbx_test" || !url.port || url.search || url.hash) {
    throw new Error("Legacy prerequisite tests require the dedicated loopback phone11_pbx_test database and explicit port");
  }
}

const pool = connectionString ? new Pool({ connectionString, ssl: false }) : null;
const schema = `phone11_legacy_default_${randomBytes(8).toString("hex")}`;
let migration: string;

type FixtureOptions = {
  defaultSql?: string | null;
  tenantType?: string;
  extensionPk?: boolean;
  tenantPk?: boolean;
  tenantNullable?: boolean;
  identity?: boolean;
};

async function fixture(options: FixtureOptions = {}) {
  await pool!.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);
  await pool!.query(`CREATE SCHEMA ${schema}`);
  await pool!.query(`CREATE TABLE ${schema}.tenants(id INTEGER ${options.tenantPk === false ? "" : "PRIMARY KEY"}, name TEXT NOT NULL)`);
  await pool!.query(`CREATE TABLE ${schema}.extensions(
    id INTEGER ${options.extensionPk === false ? "" : "PRIMARY KEY"},
    tenant_id ${options.tenantType ?? "INTEGER"}${options.identity ? " GENERATED BY DEFAULT AS IDENTITY" : options.defaultSql === null ? "" : ` DEFAULT ${options.defaultSql ?? "1"}`}${options.tenantNullable === false ? " NOT NULL" : ""},
    extension_number TEXT NOT NULL)`);
  await pool!.query(`INSERT INTO ${schema}.tenants VALUES (10,'A'),(20,'B')`);
  await pool!.query(`INSERT INTO ${schema}.extensions(id,tenant_id,extension_number) VALUES (101,10,'1001'),(201,20,'2001')`);
}

async function clientForTarget(options: { database?: string | null; targetSchema?: string | null; ack?: string | null } = {}) {
  const client = await pool!.connect();
  await client.query("RESET phone11.expected_database");
  await client.query("RESET phone11.expected_schema");
  await client.query("RESET phone11.allow_reviewed_legacy_tenant_default_removal");
  await client.query(`SET search_path TO ${schema}`);
  if (options.database !== null) {
    await client.query("SELECT set_config('phone11.expected_database', $1, false)", [options.database ?? "phone11_pbx_test"]);
  }
  if (options.targetSchema !== null) {
    await client.query("SELECT set_config('phone11.expected_schema', $1, false)", [options.targetSchema ?? schema]);
  }
  if (options.ack !== null) {
    await client.query("SELECT set_config('phone11.allow_reviewed_legacy_tenant_default_removal', $1, false)", [options.ack ?? "true"]);
  }
  return client;
}

async function apply(client: PoolClient) {
  try { await client.query(migration); }
  catch (error) { await client.query("ROLLBACK"); throw error; }
}

async function catalog() {
  const result = await pool!.query(`
    SELECT a.attnotnull, pg_get_expr(d.adbin,d.adrelid) AS tenant_default,
           c.conname, c.convalidated, c.condeferrable,
           rn.nspname AS referenced_schema, r.relname AS referenced_table
      FROM pg_attribute a
      JOIN pg_class e ON e.oid=a.attrelid
      JOIN pg_namespace n ON n.oid=e.relnamespace
      LEFT JOIN pg_attrdef d ON d.adrelid=e.oid AND d.adnum=a.attnum
      LEFT JOIN pg_constraint c ON c.conrelid=e.oid AND c.conname='phone11_extensions_tenant_fk'
      LEFT JOIN pg_class r ON r.oid=c.confrelid
      LEFT JOIN pg_namespace rn ON rn.oid=r.relnamespace
     WHERE n.nspname=$1 AND e.relname='extensions' AND a.attname='tenant_id'`, [schema]);
  return result.rows[0];
}

async function unchangedAfterFailure(operation: (client: PoolClient) => Promise<unknown>, code = "55000") {
  const before = await catalog();
  const rows = (await pool!.query(`SELECT * FROM ${schema}.extensions ORDER BY id`)).rows;
  const client = await clientForTarget();
  try { await expect(operation(client)).rejects.toMatchObject({ code }); }
  finally { client.release(); }
  expect(await catalog()).toEqual(before);
  expect((await pool!.query(`SELECT * FROM ${schema}.extensions ORDER BY id`)).rows).toEqual(rows);
}

describe.skipIf(!connectionString)("Phone11 legacy tenant-default upgrade on isolated PostgreSQL", () => {
  beforeAll(async () => {
    migration = await readFile(new URL("../server/pbx/extension-tenant-legacy-default-prerequisites.sql", import.meta.url), "utf8");
  });
  afterAll(async () => {
    if (pool) {
      await pool.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);
      await pool.end();
    }
  });

  it("removes only DEFAULT 1, sets NOT NULL and a validated same-schema FK, and replays with no DDL", async () => {
    await fixture();
    const before = (await pool!.query(`SELECT * FROM ${schema}.extensions ORDER BY id`)).rows;
    const client = await clientForTarget();
    try {
      await apply(client);
      expect(await catalog()).toMatchObject({ attnotnull: true, tenant_default: null,
        conname: "phone11_extensions_tenant_fk", convalidated: true, condeferrable: false,
        referenced_schema: schema, referenced_table: "tenants" });
      expect((await pool!.query(`SELECT * FROM ${schema}.extensions ORDER BY id`)).rows).toEqual(before);
      const beforeReplay = await pool!.query(`SELECT c.oid, c.xmin::text AS xmin FROM pg_constraint c
        JOIN pg_class e ON e.oid=c.conrelid JOIN pg_namespace n ON n.oid=e.relnamespace
        WHERE n.nspname=$1 AND c.conname='phone11_extensions_tenant_fk'`, [schema]);
      await apply(client);
      const afterReplay = await pool!.query(`SELECT c.oid, c.xmin::text AS xmin FROM pg_constraint c
        JOIN pg_class e ON e.oid=c.conrelid JOIN pg_namespace n ON n.oid=e.relnamespace
        WHERE n.nspname=$1 AND c.conname='phone11_extensions_tenant_fk'`, [schema]);
      expect(afterReplay.rows).toEqual(beforeReplay.rows);
      await expect(pool!.query(`INSERT INTO ${schema}.extensions(id,extension_number) VALUES (301,'3001')`))
        .rejects.toMatchObject({ code: "23502" });
      await pool!.query(`INSERT INTO ${schema}.extensions(id,tenant_id,extension_number) VALUES (301,20,'3001')`);
      await expect(pool!.query(`INSERT INTO ${schema}.extensions(id,tenant_id,extension_number) VALUES (302,99,'3002')`))
        .rejects.toMatchObject({ code: "23503" });
    } finally { client.release(); }
  });

  for (const invalid of ["NULL", "orphan"] as const) {
    it(`rolls back with DEFAULT 1 retained for ${invalid} rows`, async () => {
      await fixture();
      await pool!.query(`INSERT INTO ${schema}.extensions VALUES (301,${invalid === "NULL" ? "NULL" : "99"},'3001')`);
      await unchangedAfterFailure(apply, "23514");
    });
  }

  it("refuses absent or mismatched pins and absent or nonexact acknowledgement", async () => {
    for (const options of [
      { database: "wrong_database" }, { targetSchema: "wrong_schema" },
      { database: null }, { targetSchema: null }, { ack: null }, { ack: "TRUE" },
    ]) {
      await fixture();
      const before = await catalog();
      const client = await clientForTarget(options);
      try { await expect(apply(client)).rejects.toMatchObject({ code: "55000" }); }
      finally { client.release(); }
      expect(await catalog()).toEqual(before);
    }
  });

  it("pins operator lookup before comparing a caller-controlled earlier namespace", async () => {
    await fixture();
    const hostileSchema = `${schema}_earlier`;
    await pool!.query(`CREATE SCHEMA ${hostileSchema}`);
    try {
      await pool!.query(`CREATE FUNCTION ${hostileSchema}.always_false(text,text)
        RETURNS boolean LANGUAGE SQL IMMUTABLE AS $$ SELECT false $$`);
      await pool!.query(`CREATE OPERATOR ${hostileSchema}.<> (
        LEFTARG = text, RIGHTARG = text, PROCEDURE = ${hostileSchema}.always_false
      )`);
      const before = await catalog();
      const rows = (await pool!.query(`SELECT * FROM ${schema}.extensions ORDER BY id`)).rows;
      const client = await clientForTarget({ database: "wrong_database", targetSchema: schema });
      try {
        await client.query(`SET search_path TO ${hostileSchema}, ${schema}, pg_catalog`);
        expect((await client.query("SELECT 'a'::text <> 'b'::text AS result")).rows[0].result).toBe(false);
        await expect(apply(client)).rejects.toMatchObject({ code: "55000" });
      } finally { client.release(); }
      expect(await catalog()).toEqual(before);
      expect((await pool!.query(`SELECT * FROM ${schema}.extensions ORDER BY id`)).rows).toEqual(rows);
    } finally { await pool!.query(`DROP SCHEMA ${hostileSchema} CASCADE`); }
  });

  for (const [label, options] of [
    ["missing default", { defaultSql: null }],
    ["another constant", { defaultSql: "2" }],
    ["function default", { defaultSql: "(1 + random()::integer)" }],
    ["wrong type", { tenantType: "BIGINT" }],
    ["missing extension PK", { extensionPk: false }],
    ["missing tenant PK", { tenantPk: false }],
    ["tenant identity", { identity: true }],
    ["already NOT NULL", { tenantNullable: false }],
  ] as const) {
    it(`refuses ${label} while retaining the catalog and rows`, async () => {
      await fixture(options);
      await unchangedAfterFailure(apply);
    });
  }

  for (const [label, ddl] of [
    ["partial named FK", `ALTER TABLE ${schema}.extensions ADD CONSTRAINT phone11_extensions_tenant_fk FOREIGN KEY (tenant_id) REFERENCES ${schema}.tenants(id)`],
    ["unnamed conflicting FK", `ALTER TABLE ${schema}.extensions ADD CONSTRAINT other_tenant_fk FOREIGN KEY (tenant_id) REFERENCES ${schema}.tenants(id)`],
    ["unvalidated FK", `ALTER TABLE ${schema}.extensions ADD CONSTRAINT phone11_extensions_tenant_fk FOREIGN KEY (tenant_id) REFERENCES ${schema}.tenants(id) NOT VALID`],
    ["deferred FK", `ALTER TABLE ${schema}.extensions ADD CONSTRAINT phone11_extensions_tenant_fk FOREIGN KEY (tenant_id) REFERENCES ${schema}.tenants(id) DEFERRABLE`],
    ["non-FK named constraint", `ALTER TABLE ${schema}.extensions ADD CONSTRAINT phone11_extensions_tenant_fk CHECK (tenant_id > 0)`],
  ] as const) {
    it(`refuses ${label}`, async () => {
      await fixture();
      await pool!.query(ddl);
      await unchangedAfterFailure(apply);
    });
  }

  it("refuses a named FK to tenants in another schema", async () => {
    await fixture();
    const otherSchema = `${schema}_other`;
    await pool!.query(`CREATE SCHEMA ${otherSchema}`);
    try {
      await pool!.query(`CREATE TABLE ${otherSchema}.tenants(id INTEGER PRIMARY KEY)`);
      await pool!.query(`INSERT INTO ${otherSchema}.tenants VALUES (10),(20)`);
      await pool!.query(`ALTER TABLE ${schema}.extensions ADD CONSTRAINT phone11_extensions_tenant_fk
        FOREIGN KEY (tenant_id) REFERENCES ${otherSchema}.tenants(id)`);
      await unchangedAfterFailure(apply);
    } finally { await pool!.query(`DROP SCHEMA ${otherSchema} CASCADE`); }
  });

  it("refuses a multi-column named FK", async () => {
    await fixture();
    await pool!.query(`ALTER TABLE ${schema}.tenants ADD COLUMN org INTEGER NOT NULL DEFAULT 7`);
    await pool!.query(`ALTER TABLE ${schema}.tenants ADD CONSTRAINT tenants_id_org_unique UNIQUE (id,org)`);
    await pool!.query(`ALTER TABLE ${schema}.extensions ADD COLUMN org INTEGER NOT NULL DEFAULT 7`);
    await pool!.query(`ALTER TABLE ${schema}.extensions ADD CONSTRAINT phone11_extensions_tenant_fk
      FOREIGN KEY (tenant_id,org) REFERENCES ${schema}.tenants(id,org)`);
    await unchangedAfterFailure(apply);
  });

  it("refuses a temporary namespace even with matching pins", async () => {
    const client = await pool!.connect();
    try {
      await client.query("CREATE TEMP TABLE tenants(id INTEGER PRIMARY KEY)");
      await client.query("CREATE TEMP TABLE extensions(id INTEGER PRIMARY KEY, tenant_id INTEGER DEFAULT 1)");
      await client.query("SET search_path TO pg_temp");
      const temporarySchema = (await client.query("SELECT current_schema() AS name")).rows[0].name as string;
      await client.query("SELECT set_config('phone11.expected_database','phone11_pbx_test',false)");
      await client.query("SELECT set_config('phone11.expected_schema',$1,false)", [temporarySchema]);
      await client.query("SELECT set_config('phone11.allow_reviewed_legacy_tenant_default_removal','true',false)");
      await expect(apply(client)).rejects.toMatchObject({ code: "55000" });
      const check = await client.query("SELECT pg_get_expr(d.adbin,d.adrelid) AS tenant_default FROM pg_attribute a JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid='pg_temp.extensions'::regclass AND a.attname='tenant_id'");
      expect(check.rows[0].tenant_default).toBe("1");
    } finally {
      await client.query("DROP TABLE IF EXISTS pg_temp.extensions");
      await client.query("DROP TABLE IF EXISTS pg_temp.tenants");
      client.release();
    }
  });

  for (const [label, statements] of [
    ["extensions as an inheritance parent", [
      `CREATE TABLE ${schema}.extensions_child () INHERITS (${schema}.extensions)`,
      `INSERT INTO ${schema}.extensions_child(id,tenant_id,extension_number) VALUES (301,10,'3001')`,
    ]],
    ["extensions as an inheritance child", [
      `CREATE TABLE ${schema}.extensions_parent(id INTEGER,tenant_id INTEGER DEFAULT 1,extension_number TEXT NOT NULL)`,
      `ALTER TABLE ${schema}.extensions INHERIT ${schema}.extensions_parent`,
    ]],
    ["tenants as an inheritance parent", [
      `CREATE TABLE ${schema}.tenants_child () INHERITS (${schema}.tenants)`,
      `INSERT INTO ${schema}.tenants_child(id,name) VALUES (30,'C')`,
    ]],
    ["tenants as an inheritance child", [
      `CREATE TABLE ${schema}.tenants_parent(id INTEGER,name TEXT NOT NULL)`,
      `ALTER TABLE ${schema}.tenants INHERIT ${schema}.tenants_parent`,
    ]],
  ] as const) {
    it(`refuses ${label} while retaining catalog and rows`, async () => {
      await fixture();
      for (const statement of statements) await pool!.query(statement);
      const beforeHierarchy = (await pool!.query(`SELECT count(*)::int AS n FROM pg_inherits i
        WHERE i.inhrelid IN ('${schema}.extensions'::regclass,'${schema}.tenants'::regclass)
           OR i.inhparent IN ('${schema}.extensions'::regclass,'${schema}.tenants'::regclass)`)).rows[0].n;
      expect(beforeHierarchy).toBeGreaterThan(0);
      await unchangedAfterFailure(apply);
      const afterHierarchy = (await pool!.query(`SELECT count(*)::int AS n FROM pg_inherits i
        WHERE i.inhrelid IN ('${schema}.extensions'::regclass,'${schema}.tenants'::regclass)
           OR i.inhparent IN ('${schema}.extensions'::regclass,'${schema}.tenants'::regclass)`)).rows[0].n;
      expect(afterHierarchy).toBe(beforeHierarchy);
    });
  }

  it("refuses a partition leaf with ordinary relkind and inherited primary key", async () => {
    await fixture();
    await pool!.query(`DROP TABLE ${schema}.extensions`);
    await pool!.query(`CREATE TABLE ${schema}.extensions_parent(
      id INTEGER PRIMARY KEY, tenant_id INTEGER DEFAULT 1, extension_number TEXT NOT NULL
    ) PARTITION BY RANGE (id)`);
    await pool!.query(`CREATE TABLE ${schema}.extensions PARTITION OF ${schema}.extensions_parent
      FOR VALUES FROM (0) TO (1000)`);
    await pool!.query(`INSERT INTO ${schema}.extensions(id,tenant_id,extension_number) VALUES (101,10,'1001'),(201,20,'2001')`);
    const shape = await pool!.query(`SELECT relkind, relispartition FROM pg_class WHERE oid='${schema}.extensions'::regclass`);
    expect(shape.rows[0]).toEqual({ relkind: "r", relispartition: true });
    await unchangedAfterFailure(apply);
  });

  it("holds both targets against an inheritance attachment during catalog checks", async () => {
    await fixture();
    const holder = await pool!.connect();
    const contender = await pool!.connect();
    try {
      await holder.query("BEGIN");
      await holder.query(`LOCK TABLE ${schema}.extensions IN ACCESS EXCLUSIVE MODE`);
      await holder.query(`LOCK TABLE ${schema}.tenants IN SHARE ROW EXCLUSIVE MODE`);
      await contender.query("SET lock_timeout = '200ms'");
      await expect(contender.query(`CREATE TABLE ${schema}.extensions_child () INHERITS (${schema}.extensions)`))
        .rejects.toMatchObject({ code: "55P03" });
      await expect(contender.query(`CREATE TABLE ${schema}.tenants_child () INHERITS (${schema}.tenants)`))
        .rejects.toMatchObject({ code: "55P03" });
    } finally {
      await holder.query("ROLLBACK");
      await contender.query("RESET lock_timeout");
      holder.release();
      contender.release();
    }
    expect((await pool!.query(`SELECT count(*)::int AS n FROM pg_inherits i
      WHERE i.inhparent IN ('${schema}.extensions'::regclass,'${schema}.tenants'::regclass)`)).rows[0].n).toBe(0);
  });

  it("refuses an unvalidated no-default replay state", async () => {
    await fixture({ defaultSql: null, tenantNullable: false });
    await pool!.query(`ALTER TABLE ${schema}.extensions ADD CONSTRAINT phone11_extensions_tenant_fk
      FOREIGN KEY (tenant_id) REFERENCES ${schema}.tenants(id) NOT VALID`);
    await unchangedAfterFailure(apply);
  });

  it("refuses replay when child-side internal FK triggers are disabled", async () => {
    await fixture();
    const client = await clientForTarget();
    try {
      await apply(client);
      await pool!.query(`ALTER TABLE ${schema}.extensions DISABLE TRIGGER ALL`);
      const before = await catalog();
      const rows = (await pool!.query(`SELECT * FROM ${schema}.extensions ORDER BY id`)).rows;
      const disabled = await pool!.query(`SELECT count(*)::int AS n FROM pg_trigger t
        WHERE t.tgrelid='${schema}.extensions'::regclass AND t.tgisinternal AND t.tgenabled='D'`);
      expect(disabled.rows[0].n).toBe(2);
      await expect(apply(client)).rejects.toMatchObject({ code: "55000" });
      expect(await catalog()).toEqual(before);
      expect((await pool!.query(`SELECT * FROM ${schema}.extensions ORDER BY id`)).rows).toEqual(rows);
      expect((await pool!.query(`SELECT count(*)::int AS n FROM pg_trigger t
        WHERE t.tgrelid='${schema}.extensions'::regclass AND t.tgisinternal AND t.tgenabled='D'`)).rows[0].n).toBe(2);
    } finally {
      await pool!.query(`ALTER TABLE ${schema}.extensions ENABLE TRIGGER ALL`);
      client.release();
    }
  });

  it("refuses a replica session before any catalog change", async () => {
    await fixture();
    const client = await clientForTarget();
    const before = await catalog();
    try {
      await client.query("SET session_replication_role = replica");
      await expect(apply(client)).rejects.toMatchObject({ code: "55000" });
      expect(await catalog()).toEqual(before);
    } finally {
      await client.query("RESET session_replication_role");
      client.release();
    }
  });

  it("refuses REPEATABLE READ and SERIALIZABLE even when wrapped in a transaction", async () => {
    for (const isolation of ["REPEATABLE READ", "SERIALIZABLE"]) {
      await fixture();
      const client = await clientForTarget();
      try {
        await client.query(`BEGIN ISOLATION LEVEL ${isolation}`);
        await client.query(`SELECT id FROM ${schema}.extensions LIMIT 1`); // establish an older snapshot
        await expect(apply(client)).rejects.toMatchObject({ code: "55000" });
      } finally { client.release(); }
      expect(await catalog()).toMatchObject({ attnotnull: false, tenant_default: "1", conname: null });
    }
  });

  it("refuses a session whose default transaction isolation is not READ COMMITTED", async () => {
    await fixture();
    const client = await clientForTarget();
    try {
      await client.query("SET default_transaction_isolation TO 'repeatable read'");
      await expect(apply(client)).rejects.toMatchObject({ code: "55000" });
    } finally {
      await client.query("RESET default_transaction_isolation");
      client.release();
    }
    expect(await catalog()).toMatchObject({ attnotnull: false, tenant_default: "1", conname: null });
  });

  it("times out behind an extension reader and rolls back without partial DDL", async () => {
    await fixture();
    const blocker = await pool!.connect();
    const client = await clientForTarget();
    try {
      await blocker.query("BEGIN");
      await blocker.query(`SELECT id FROM ${schema}.extensions LIMIT 1`);
      await expect(apply(client)).rejects.toMatchObject({ code: "55P03" });
    } finally {
      await blocker.query("ROLLBACK");
      blocker.release();
      client.release();
    }
    expect(await catalog()).toMatchObject({ attnotnull: false, tenant_default: "1", conname: null });
  }, 15000);
});
