#!/bin/sh
# Isolated FreeSWITCH callback probe only. Never install this in production.
# The harness sets /probe/current-case before each synthetic call, then copies
# the four private case directories and this exact runner out of the clone.
set -eu
umask 077

phase=${1:-}
case_name=$(cat /probe/current-case)
case "$case_name" in
  answered|no_answer_dtmf|caller_hangup|early_abandon) ;;
  *) exit 1 ;;
esac
case "$phase" in
  admit|complete) ;;
  *) exit 1 ;;
esac
test -d "/probe/$case_name"
(
  set -C
  cat > "/probe/$case_name/$phase.json"
)
if [ "$phase" = complete ]; then
  # The JSON is generated by the reviewed Lua hook in this synthetic clone.
  # Accept only a plain /probe path; reject escapes rather than guessing.
  file_path=$(sed -n 's/.*"voicemailFilePath":"\([^"]*\)".*/\1/p' "/probe/$case_name/complete.json")
  case "$file_path" in
    /probe/*.wav) ;;
    *) exit 1 ;;
  esac
  case "$file_path" in
    *..*|*\\*) exit 1 ;;
  esac
  test -f "$file_path" && test ! -L "$file_path"
  size_before=$(/usr/bin/stat -c %s -- "$file_path")
  mtime_before=$(/usr/bin/stat -c %Y -- "$file_path")
  complete_mtime=$(/usr/bin/stat -c %Y -- "/probe/$case_name/complete.json")
  digest=$(/usr/bin/sha256sum -- "$file_path")
  digest=${digest%% *}
  size_after=$(/usr/bin/stat -c %s -- "$file_path")
  mtime_after=$(/usr/bin/stat -c %Y -- "$file_path")
  test "$size_before" = "$size_after" && test "$mtime_before" = "$mtime_after"
  observed=$(/usr/bin/date +%s)
  (
    set -C
    printf 'path=%s\nsha256=%s\nsize=%s\nmtime=%s\ncomplete_mtime=%s\nobserved=%s\n' \
      "$file_path" "$digest" "$size_after" "$mtime_after" "$complete_mtime" "$observed" \
      > "/probe/$case_name/complete-media.txt"
  )
fi
