import { createHash, randomBytes } from "node:crypto";
import type { Pool, PoolClient } from "pg";
import { z } from "zod";

export const ANDROID_STAGING_SEED = {
  project: "phone11-stage-20260914",
  instance: "phone11-stage-20260914:asia-southeast1:phone11-stage-wake-pg",
  database: "phone11_wake_stage",
  domain: "sip.stage.phone11.test",
  transport: "UDP",
  port: 15060,
  extension: "7101",
  organizationId: 1,
  tenantId: 1,
  userId: 1,
  extensionId: 7101,
} as const;

export type AndroidStagingSeedConfig = {
  apply: boolean;
  email: string;
};

const emailSchema = z.email().transform((value) => value.trim().toLowerCase());

export function readAndroidStagingSeedConfig(input: {
  apply?: boolean;
  confirmEmptyDatabase?: boolean;
  project?: string;
  instance?: string;
  database?: string;
  extension?: string;
  domain?: string;
  email?: string;
}): AndroidStagingSeedConfig {
  const exact = (
    actual: string | undefined,
    expected: string,
    label: string,
  ) => {
    if (actual !== expected)
      throw new Error(`Android staging seed ${label} mismatch`);
  };
  exact(input.project, ANDROID_STAGING_SEED.project, "project");
  exact(input.instance, ANDROID_STAGING_SEED.instance, "instance");
  exact(input.database, ANDROID_STAGING_SEED.database, "database");
  exact(input.extension, ANDROID_STAGING_SEED.extension, "extension");
  exact(input.domain, ANDROID_STAGING_SEED.domain, "domain");
  const email = emailSchema.parse(input.email);
  if (input.apply && input.confirmEmptyDatabase !== true) {
    throw new Error(
      "Android staging seed apply requires --confirm-empty-database",
    );
  }
  return { apply: input.apply === true, email };
}

export const canonicalAuthoritySchemaSql = `
CREATE TABLE organizations (
  id INTEGER PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  plan VARCHAR(64) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE tenants (
  id INTEGER PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  plan VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL CHECK (status IN ('active','inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);
CREATE SEQUENCE users_id_seq;
CREATE TABLE users (
  id INTEGER PRIMARY KEY DEFAULT nextval('users_id_seq'::regclass),
  "openId" VARCHAR(64) NOT NULL UNIQUE,
  name TEXT,
  email VARCHAR(320),
  "loginMethod" VARCHAR(64),
  role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user','admin')),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  "lastSignedIn" TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE extensions (
  id INTEGER PRIMARY KEY,
  org_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
  tenant_id INTEGER NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  user_id INTEGER REFERENCES users(id) ON DELETE RESTRICT,
  extension_number VARCHAR(32) NOT NULL,
  display_name VARCHAR(128),
  type VARCHAR(32) NOT NULL DEFAULT 'user',
  sip_username VARCHAR(64),
  sip_domain VARCHAR(128),
  sip_password VARCHAR(128),
  caller_id_name VARCHAR(128),
  caller_id_number VARCHAR(64),
  transport VARCHAR(16) NOT NULL DEFAULT 'UDP',
  status VARCHAR(32) NOT NULL CHECK (status IN ('active','inactive')),
  voicemail_enabled BOOLEAN NOT NULL DEFAULT false,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (tenant_id, extension_number)
);
CREATE TABLE user_extensions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  extension_id INTEGER NOT NULL REFERENCES extensions(id) ON DELETE CASCADE,
  is_primary BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (user_id, extension_id)
);
CREATE TABLE sip_accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  org_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
  extension_id INTEGER NOT NULL UNIQUE REFERENCES extensions(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE RESTRICT,
  sip_username VARCHAR(64) NOT NULL,
  sip_domain VARCHAR(128) NOT NULL,
  ha1 VARCHAR(128),
  ha1b VARCHAR(128),
  secret_ciphertext BYTEA,
  secret_iv BYTEA,
  secret_tag BYTEA,
  dek_id VARCHAR(64),
  transport_preference VARCHAR(16) NOT NULL DEFAULT 'UDP',
  status VARCHAR(32) NOT NULL CHECK (status IN ('active','inactive')),
  last_registered_at TIMESTAMPTZ,
  last_registered_contact TEXT,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (tenant_id, sip_username, sip_domain)
);
CREATE TABLE subscriber (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  domain VARCHAR(128) NOT NULL,
  password VARCHAR(128) NOT NULL,
  ha1 VARCHAR(128) NOT NULL,
  ha1b VARCHAR(128) NOT NULL,
  email_address VARCHAR(320) NOT NULL DEFAULT '',
  rpid VARCHAR(128),
  UNIQUE (username, domain)
);
CREATE UNIQUE INDEX subscriber_username_lower_domain_unique ON subscriber(username, lower(domain));
CREATE TABLE did_numbers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
  tenant_id INTEGER NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  number VARCHAR(64) NOT NULL,
  description TEXT,
  destination_type VARCHAR(32) NOT NULL DEFAULT 'extension',
  destination_value VARCHAR(64),
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);`;

const canonicalTables = [
  "organizations",
  "tenants",
  "users",
  "extensions",
  "user_extensions",
  "sip_accounts",
  "subscriber",
  "did_numbers",
] as const;

async function requireEmptyDatabase(client: Pick<PoolClient, "query">) {
  const current = await client.query<{ database: string }>(
    "SELECT current_database() AS database",
  );
  if (current.rows[0]?.database !== ANDROID_STAGING_SEED.database) {
    throw new Error(
      "Connected database is not the isolated Android staging database",
    );
  }
  const existing = await client.query<{ table_name: string }>(
    `SELECT table_name FROM information_schema.tables
       WHERE table_schema='public' AND table_type='BASE TABLE'
       ORDER BY table_name`,
  );
  if (existing.rows.length) {
    throw new Error("Android staging seed requires an empty public schema");
  }
}

export async function inspectAndroidStagingSeed(
  database: Pick<Pool, "connect">,
) {
  const client = await database.connect();
  try {
    await requireEmptyDatabase(client);
    return {
      readyToApply: true,
      project: ANDROID_STAGING_SEED.project,
      database: ANDROID_STAGING_SEED.database,
      canonicalTables: [...canonicalTables],
      syntheticSipUri: `sip:${ANDROID_STAGING_SEED.extension}@${ANDROID_STAGING_SEED.domain}`,
      sipTransport: ANDROID_STAGING_SEED.transport,
      sipPort: ANDROID_STAGING_SEED.port,
      createsSession: false,
      createsPushDevice: false,
      createsWakeBinding: false,
    };
  } finally {
    client.release();
  }
}

export async function applyAndroidStagingSeed(
  database: Pick<Pool, "connect">,
  config: AndroidStagingSeedConfig,
) {
  if (!config.apply)
    throw new Error("Android staging seed is plan-only without --apply");
  const client = await database.connect();
  try {
    await client.query("BEGIN");
    await client.query(
      "SET LOCAL lock_timeout='5s'; SET LOCAL statement_timeout='30s'",
    );
    await client.query("SELECT pg_advisory_xact_lock(7101, 20260914)");
    await requireEmptyDatabase(client);
    await client.query(canonicalAuthoritySchemaSql);

    const sipPassword = randomBytes(32).toString("base64url");
    const digest = (identity: string) =>
      createHash("md5")
        .update(`${identity}:${ANDROID_STAGING_SEED.domain}:${sipPassword}`)
        .digest("hex");
    const ha1 = digest(ANDROID_STAGING_SEED.extension);
    const ha1b = digest(
      `${ANDROID_STAGING_SEED.extension}@${ANDROID_STAGING_SEED.domain}`,
    );

    await client.query(
      "INSERT INTO organizations(id,name,plan) VALUES($1,$2,$3)",
      [ANDROID_STAGING_SEED.organizationId, "Phone11 Android Staging", "lab"],
    );
    await client.query(
      "INSERT INTO tenants(id,name,plan,status) VALUES($1,$2,$3,'active')",
      [ANDROID_STAGING_SEED.tenantId, "Phone11 Android Staging", "lab"],
    );
    await client.query(
      `INSERT INTO users(id,"openId",name,email,"loginMethod",role)
       VALUES($1,$2,$3,$4,'phone11','user')`,
      [
        ANDROID_STAGING_SEED.userId,
        "phone11:staging:android:7101",
        "Phone11 Android Staging 7101",
        config.email,
      ],
    );
    await client.query("SELECT setval('users_id_seq', $1, true)", [
      ANDROID_STAGING_SEED.userId,
    ]);
    await client.query(
      `INSERT INTO extensions
       (id,org_id,tenant_id,user_id,extension_number,display_name,type,sip_username,sip_domain,
        transport,status,voicemail_enabled)
       VALUES($1,$2,$3,$4,$5,$6,'user',$5,$7,$8,'active',false)`,
      [
        ANDROID_STAGING_SEED.extensionId,
        ANDROID_STAGING_SEED.organizationId,
        ANDROID_STAGING_SEED.tenantId,
        ANDROID_STAGING_SEED.userId,
        ANDROID_STAGING_SEED.extension,
        "Android Staging 7101",
        ANDROID_STAGING_SEED.domain,
        ANDROID_STAGING_SEED.transport,
      ],
    );
    await client.query(
      "INSERT INTO user_extensions(user_id,extension_id,is_primary) VALUES($1,$2,true)",
      [ANDROID_STAGING_SEED.userId, ANDROID_STAGING_SEED.extensionId],
    );
    await client.query(
      `INSERT INTO sip_accounts
       (tenant_id,org_id,extension_id,user_id,sip_username,sip_domain,ha1,ha1b,transport_preference,status)
       VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'active')`,
      [
        ANDROID_STAGING_SEED.tenantId,
        ANDROID_STAGING_SEED.organizationId,
        ANDROID_STAGING_SEED.extensionId,
        ANDROID_STAGING_SEED.userId,
        ANDROID_STAGING_SEED.extension,
        ANDROID_STAGING_SEED.domain,
        ha1,
        ha1b,
        ANDROID_STAGING_SEED.transport,
      ],
    );
    await client.query(
      `INSERT INTO subscriber(username,domain,password,ha1,ha1b,email_address)
       VALUES($1,$2,$3,$4,$5,$6)`,
      [
        ANDROID_STAGING_SEED.extension,
        ANDROID_STAGING_SEED.domain,
        sipPassword,
        ha1,
        ha1b,
        config.email,
      ],
    );
    const proof = await client.query<{ count: number }>(`
      SELECT count(*)::integer AS count
        FROM users u
        JOIN user_extensions ue ON ue.user_id=u.id
        JOIN extensions e ON e.id=ue.extension_id AND e.user_id=u.id
        JOIN tenants t ON t.id=e.tenant_id AND t.status='active'
        JOIN sip_accounts sa ON sa.extension_id=e.id AND sa.tenant_id=t.id
        JOIN subscriber sub ON sub.username=sa.sip_username AND lower(sub.domain)=lower(sa.sip_domain)
       WHERE u.id=1 AND u.role='user' AND e.id=7101 AND e.extension_number='7101'
         AND e.status='active' AND e.deleted_at IS NULL AND ue.is_primary
         AND sa.status='active' AND sa.deleted_at IS NULL
         AND e.transport='UDP' AND sa.transport_preference='UDP'
         AND ('sip:'||sa.sip_username||'@'||lower(sa.sip_domain))='sip:7101@sip.stage.phone11.test'
         AND length(sub.password)>0
    `);
    if (proof.rows[0]?.count !== 1)
      throw new Error("Synthetic Android staging authority proof failed");
    await client.query("COMMIT");
    return {
      seeded: true,
      userId: ANDROID_STAGING_SEED.userId,
      tenantId: ANDROID_STAGING_SEED.tenantId,
      extensionId: ANDROID_STAGING_SEED.extensionId,
      sipUri: `sip:${ANDROID_STAGING_SEED.extension}@${ANDROID_STAGING_SEED.domain}`,
    };
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
  }
}
