package ai.phone11.siprix;

import java.util.*;

/** Synthetic boundaries only: never opens SDK, media, network, or a permission prompt. */
final class AndroidConsultationTest {
  static int assertions;
  static final String REQUEST="00000000-0000-4000-8000-111111111111",TRANSFER="00000000-0000-4000-8000-222222222222";
  static void check(boolean value){assertions++;if(!value)throw new AssertionError("consultation assertion "+assertions);}
  static void fails(String code,Runnable action){try{action.run();throw new AssertionError("expected "+code);}catch(Phone11CallRuntime.Failure failure){check(code.equals(failure.code));}}
  static final class Clock implements Phone11ConsultationRuntime.Scheduler {
    long now;final List<Map.Entry<Long,Runnable>> tasks=new ArrayList<>();
    public void after(long delay,Runnable task){tasks.add(new AbstractMap.SimpleImmutableEntry<>(now+delay,task));}
    void advance(long delay){now+=delay;List<Map.Entry<Long,Runnable>> due=new ArrayList<>();for(Map.Entry<Long,Runnable> task:tasks)if(task.getKey()<=now)due.add(task);tasks.removeAll(due);for(Map.Entry<Long,Runnable> task:due)task.getValue().run();}
  }
  static class BaseEngine implements Phone11CallRuntime.Engine {
    Phone11CallRuntime.Listener listener;int account=7,call=11,invites,ends,holds,mutes,holdState;String fail;
    void command(String name){if(name.equals(fail))throw new Phone11CallRuntime.Failure("E_SIPRIX_-77");}
    public String initialize(Phone11CallRuntime.Listener value){listener=value;return "1.1.0 from 20260905_1222";}
    public void destroy(){command("destroy");} public int addAccount(Map<String,Object> config){return account;}
    public void register(int id,int expiry){} public void unregister(int id){} public void delete(int id){}
    public int invite(int acc,String destination){command("invite");invites++;return call;}
    public void answer(int id){} public void end(int id,boolean reject){command("end");ends++;}
    public void mute(int id,boolean value){command("mute");mutes++;} public void rejectVideo(int id){}
    public int holdState(int id){command("queryHold");return id==11?holdState:0;} public void toggleHold(int id){command("hold");holds++;}
    public void dtmf(int id,String digits){} public boolean speaker(){return false;} public void speaker(boolean value){}
  }
  static final class Engine extends BaseEngine {
    final List<Integer> ended=new ArrayList<>(),focused=new ArrayList<>();final List<Boolean> muted=new ArrayList<>();int transfers;
    Runnable onHold,onFocus,onTransfer;boolean failAfterFocus,failAfterTransfer,failUnmute,alreadyFocused;
    public void toggleHold(int id){super.toggleHold(id);if(onHold!=null)onHold.run();}
    public void switchCall(int id){if(alreadyFocused)throw new Phone11CallRuntime.Failure("E_SIPRIX_-1047");command("focus");focused.add(id);if(onFocus!=null)onFocus.run();if(failAfterFocus)throw new Phone11CallRuntime.Failure("E_SIPRIX_-77");}
    public void transferAttended(int original,int consult){command("transfer");check(original==11&&consult==12);transfers++;if(onTransfer!=null)onTransfer.run();if(failAfterTransfer)throw new Phone11CallRuntime.Failure("E_SIPRIX_-77");}
    public void end(int id,boolean reject){super.end(id,reject);ended.add(id);}
    public void mute(int id,boolean value){if(!value&&failUnmute)throw new Phone11CallRuntime.Failure("E_SIPRIX_-77");super.mute(id,value);muted.add(value);}
  }
  static final class Fixture {
    final Engine e=new Engine();final Clock clock=new Clock();final List<Map<String,Object>> events=new ArrayList<>();
    final Phone11CallRuntime r;final long lease;
    Fixture(){this(true);}
    Fixture(boolean enabled){r=new Phone11CallRuntime(e,events::add,enabled,clock);lease=r.acquire();r.initialize(lease);r.createAccount(lease,new HashMap<>());r.register(lease,"7",300);e.listener.registration(7,0,"SIP/2.0 200 OK");r.invite(lease,"7","sip:2002@example.test");e.listener.connected(11,false);e.call=12;}
    @SuppressWarnings("unchecked") List<Map<String,Object>> calls(){return (List<Map<String,Object>>)r.snapshot(lease).get("calls");}
    Map<String,Object> original(){return calls().get(0);}
    String phase(){return (String)original().get("consultationPhase");}
    void begin(){r.beginConsultation(lease,"11","3003",REQUEST);}
    void held(int state){e.holdState=state;e.listener.held(11,state);}
    void dial(){begin();held(1);r.continueConsultation(lease,"11",REQUEST);}
    void ready(){dial();e.listener.connected(12,false);e.listener.switched(12);check("ready".equals(phase()));}
    void cancel(){r.cancelConsultation(lease,"11",REQUEST);}
    void complete(){r.completeConsultation(lease,"11",REQUEST,TRANSFER);}
  }
  public static void main(String[] args){
    Fixture off=new Fixture(false);fails("E_UNSUPPORTED",()->off.r.beginConsultation(off.lease,"11","3003",REQUEST));check(off.e.holds==0);check(Boolean.FALSE.equals(off.r.snapshot(off.lease).get("warmTransferAvailable")));check(Boolean.FALSE.equals(Phone11ForegroundTrial.capabilities().get("transfer")));check(Boolean.TRUE.equals(Phone11ForegroundTrial.capabilities(true).get("consultationSourceCandidate")));
    Fixture f=new Fixture();String history=(String)f.original().get("historyId");check(Boolean.TRUE.equals(f.r.snapshot(f.lease).get("warmTransferAvailable")));check(f.r.acquire()==0);
    fails("E_INVALID_ARGUMENT",()->f.r.beginConsultation(f.lease,"11","sip:3003@foreign.test",REQUEST));fails("E_INVALID_ARGUMENT",()->f.r.beginConsultation(f.lease,"11","3003","made-up"));check(f.e.holds==0);
    f.begin();check("holding".equals(f.phase()));check(f.e.invites==1);check(f.e.holds==1);fails("E_CALL_STATE",()->f.r.continueConsultation(f.lease,"11",REQUEST));fails("E_CALL_STATE",()->f.begin());fails("E_CONSULTATION_ACTIVE",()->f.r.hold(f.lease,"11",false));
    f.held(2);check("holding".equals(f.phase()));check(f.e.invites==1);f.held(1);check("held_ready".equals(f.phase()));check(f.e.invites==1);fails("E_CONSULTATION_CHANGED",()->f.r.continueConsultation(f.lease,"11",TRANSFER));f.r.continueConsultation(f.lease,"11",REQUEST);check(f.e.invites==2);check(f.calls().size()==2);check(Boolean.TRUE.equals(f.calls().get(1).get("muted")));check(history.equals(f.original().get("historyId")));check(!history.equals(f.calls().get(1).get("historyId")));check("11".equals(f.calls().get(1).get("consultationParentId")));
    int parentEvent=-1,childEvent=-1;for(int i=0;i<f.events.size();i++){Object value=f.events.get(i).get("call");if(value instanceof Map){Map<?,?> c=(Map<?,?>)value;if("12".equals(c.get("consultationCallId"))&&parentEvent<0)parentEvent=i;if("12".equals(c.get("id"))&&childEvent<0)childEvent=i;}}check(parentEvent>=0&&childEvent>parentEvent);
    fails("E_ACTIVE_CALL",()->f.r.invite(f.lease,"7","4004"));fails("E_ACTIVE_CALL",()->f.r.delete(f.lease,"7"));f.e.listener.connected(12,false);check("switching".equals(f.phase()));check(f.e.focused.equals(Arrays.asList(12)));check(f.e.muted.equals(Arrays.asList(true)));f.e.listener.switched(99);check("switching".equals(f.phase()));f.e.listener.switched(12);check("ready".equals(f.phase()));check(f.e.muted.equals(Arrays.asList(true,false)));f.e.listener.connected(12,false);f.e.listener.switched(12);check(f.e.mutes==2);
    f.complete();check("transferring".equals(f.phase()));check(f.e.transfers==1);fails("E_TRANSFER_PENDING",()->f.cancel());fails("E_CALL_STATE",()->f.complete());f.e.listener.transferred(12,0);check("transferring".equals(f.phase()));f.e.listener.transferred(11,0);check("completed".equals(f.phase()));check(Boolean.FALSE.equals(f.original().get("transferPending")));check(f.e.ended.isEmpty());f.e.listener.transferred(11,503);check("completed".equals(f.phase()));
    f.e.listener.terminated(11,200);check(f.calls().size()==1);check(f.e.ended.isEmpty());f.r.end(f.lease,"12");check(f.e.ended.equals(Arrays.asList(12)));f.e.listener.terminated(12,200);check(f.calls().isEmpty());
    Fixture cancel=new Fixture();cancel.ready();cancel.cancel();check("canceling".equals(cancel.phase()));check(cancel.e.holds==1);check(cancel.e.ended.equals(Arrays.asList(12)));cancel.cancel();check(cancel.e.ends==1);cancel.e.listener.switched(11);check("canceling".equals(cancel.phase()));cancel.e.listener.terminated(12,200);check("returning".equals(cancel.phase()));check(cancel.e.holds==2);check(cancel.e.focused.equals(Arrays.asList(12)));cancel.held(2);check("restoring_audio".equals(cancel.phase()));check(cancel.e.focused.equals(Arrays.asList(12,11)));cancel.e.listener.switched(12);check("restoring_audio".equals(cancel.phase()));cancel.e.listener.switched(11);check("returned".equals(cancel.phase()));check(((Number)cancel.original().get("holdState")).intValue()==2);fails("E_CALL_STATE",()->cancel.begin());
    Fixture early=new Fixture();early.begin();early.cancel();check(early.e.holds==1);check("canceling".equals(early.phase()));early.held(1);check(early.e.holds==2);check("returning".equals(early.phase()));early.held(0);early.e.listener.switched(11);check("returned".equals(early.phase()));check(early.e.invites==1);
    Fixture inline=new Fixture();inline.e.onHold=()->inline.held(inline.e.holds==1?1:0);inline.begin();check("held_ready".equals(inline.phase()));inline.r.continueConsultation(inline.lease,"11",REQUEST);inline.e.onFocus=()->inline.e.listener.switched(12);inline.e.listener.connected(12,false);check("ready".equals(inline.phase()));inline.e.onTransfer=()->inline.e.listener.transferred(11,0);inline.complete();check("completed".equals(inline.phase()));
    Fixture badFocus=new Fixture();badFocus.dial();badFocus.e.onFocus=()->badFocus.e.listener.switched(12);badFocus.e.failAfterFocus=true;badFocus.e.listener.connected(12,false);check(!"ready".equals(badFocus.phase()));check(!badFocus.e.muted.contains(false));check(badFocus.e.ended.equals(Arrays.asList(12)));check(Boolean.TRUE.equals(badFocus.r.snapshot(badFocus.lease).get("cleanupRequired")));
    Fixture badTransfer=new Fixture();badTransfer.ready();badTransfer.e.onTransfer=()->badTransfer.e.listener.transferred(11,0);badTransfer.e.failAfterTransfer=true;fails("E_SIPRIX_-77",()->badTransfer.complete());check("transfer_failed".equals(badTransfer.phase()));check(!badTransfer.original().containsKey("transferStatusCode"));fails("E_CALL_STATE",()->badTransfer.complete());
    Fixture transferTimeout=new Fixture();transferTimeout.ready();transferTimeout.complete();transferTimeout.clock.advance(30000);check("transfer_failed".equals(transferTimeout.phase()));check(transferTimeout.calls().size()==2);check(transferTimeout.e.ends==0);check(Boolean.TRUE.equals(transferTimeout.original().get("transferPending")));check(!transferTimeout.original().containsKey("transferStatusCode"));fails("E_TRANSFER_PENDING",()->transferTimeout.cancel());transferTimeout.e.listener.transferred(11,0);check("completed".equals(transferTimeout.phase()));fails("E_CALL_STATE",()->transferTimeout.complete());
    Fixture holdTimeout=new Fixture();holdTimeout.begin();holdTimeout.clock.advance(30000);check("return_failed".equals(holdTimeout.phase()));check(holdTimeout.e.invites==1);holdTimeout.held(1);check("returning".equals(holdTimeout.phase()));holdTimeout.held(0);holdTimeout.e.listener.switched(11);check("returned".equals(holdTimeout.phase()));
    Fixture dialTimeout=new Fixture();dialTimeout.dial();dialTimeout.clock.advance(35000);check(dialTimeout.e.ended.equals(Arrays.asList(12)));check(dialTimeout.e.holds==1);dialTimeout.e.listener.connected(12,false);check(dialTimeout.e.focused.isEmpty());dialTimeout.e.listener.terminated(12,408);check(dialTimeout.e.holds==2);
    Fixture focusTimeout=new Fixture();focusTimeout.dial();focusTimeout.e.listener.connected(12,false);focusTimeout.clock.advance(5000);check(focusTimeout.e.ended.equals(Arrays.asList(12)));check(!focusTimeout.e.muted.contains(false));focusTimeout.e.listener.switched(12);check(!"ready".equals(focusTimeout.phase()));
    Fixture endTimeout=new Fixture();endTimeout.ready();endTimeout.cancel();endTimeout.clock.advance(30000);check("return_failed".equals(endTimeout.phase()));check(endTimeout.e.holds==1);endTimeout.e.listener.terminated(12,200);check(endTimeout.e.holds==2);
    Fixture remote=new Fixture();remote.ready();remote.held(3);check(remote.e.ended.equals(Arrays.asList(12)));check(remote.e.mutes==2);check(!"ready".equals(remote.phase()));
    Fixture taken=new Fixture();taken.ready();taken.e.listener.switched(11);check(taken.e.muted.equals(Arrays.asList(true,false,true)));check(taken.e.ended.equals(Arrays.asList(12)));taken.e.listener.switched(12);check(!"ready".equals(taken.phase()));
    Fixture originalEnds=new Fixture();originalEnds.ready();originalEnds.e.listener.terminated(11,200);check(originalEnds.e.ended.equals(Arrays.asList(12)));check(originalEnds.calls().size()==1);originalEnds.clock.advance(60000);check(originalEnds.e.holds==1);originalEnds.e.listener.terminated(12,200);check(originalEnds.calls().isEmpty());
    Fixture bothEnd=new Fixture();bothEnd.ready();bothEnd.r.end(bothEnd.lease,"11");check(bothEnd.e.ended.equals(Arrays.asList(12,11)));bothEnd.e.listener.terminated(12,200);check(bothEnd.e.holds==1);bothEnd.e.listener.terminated(11,200);check(bothEnd.calls().isEmpty());
    Fixture failedEnd=new Fixture();failedEnd.ready();failedEnd.e.fail="end";fails("E_SIPRIX_-77",()->failedEnd.cancel());check(Boolean.TRUE.equals(failedEnd.r.snapshot(failedEnd.lease).get("cleanupRequired")));check(failedEnd.calls().size()==2);failedEnd.e.listener.terminated(12,200);check(failedEnd.calls().size()==2);failedEnd.e.fail=null;failedEnd.r.destroy(failedEnd.lease);check(failedEnd.calls().isEmpty());
    Fixture reused=new Fixture();reused.begin();reused.held(1);reused.e.call=11;fails("E_CALL_ID_REUSED",()->reused.r.continueConsultation(reused.lease,"11",REQUEST));check(Boolean.TRUE.equals(reused.r.snapshot(reused.lease).get("cleanupRequired")));check(reused.calls().size()==1);
    Fixture stale=new Fixture();stale.ready();Phone11CallRuntime.Listener old=stale.e.listener;stale.r.destroy(stale.lease);stale.r.initialize(stale.lease);int before=stale.events.size();old.held(11,1);old.connected(12,false);old.switched(12);old.transferred(11,0);old.terminated(12,200);stale.clock.advance(60000);check(stale.events.size()==before);check(stale.calls().isEmpty());fails("E_CONSULTATION_CHANGED",()->stale.cancel());
    Fixture logout=new Fixture();logout.ready();logout.r.release(logout.lease);long newLease=logout.r.acquire();fails("E_STALE_BRIDGE",()->logout.r.completeConsultation(logout.lease,"11",REQUEST,TRANSFER));logout.r.initialize(newLease);logout.clock.advance(60000);check(((List<?>)logout.r.snapshot(newLease).get("calls")).isEmpty());
    Fixture endBeforeHeld=new Fixture();endBeforeHeld.begin();endBeforeHeld.r.end(endBeforeHeld.lease,"11");endBeforeHeld.held(1);check(!"held_ready".equals(endBeforeHeld.phase()));fails("E_CONSULTATION_CHANGED",()->endBeforeHeld.r.continueConsultation(endBeforeHeld.lease,"11",REQUEST));check(endBeforeHeld.e.invites==1);
    Fixture consultEndsFirst=new Fixture();consultEndsFirst.ready();consultEndsFirst.complete();consultEndsFirst.e.listener.terminated(12,200);check(consultEndsFirst.calls().size()==1);check(consultEndsFirst.e.holds==1);consultEndsFirst.clock.advance(30000);check("transfer_failed".equals(consultEndsFirst.phase()));check(Boolean.TRUE.equals(consultEndsFirst.original().get("transferPending")));check(!consultEndsFirst.original().containsKey("transferStatusCode"));consultEndsFirst.e.listener.transferred(11,503);check(Boolean.FALSE.equals(consultEndsFirst.original().get("transferPending")));
    Fixture waitingOriginal=new Fixture();waitingOriginal.ready();waitingOriginal.complete();waitingOriginal.e.listener.transferred(11,0);waitingOriginal.e.listener.terminated(11,200);waitingOriginal.e.listener.incoming(13,7,false,"sip:4004@example.test");check(waitingOriginal.calls().size()==1);check(waitingOriginal.e.ended.equals(Arrays.asList(13)));
    for(String command:Arrays.asList("queryHold","hold")){Fixture rejectedHold=new Fixture();rejectedHold.e.fail=command;fails("E_SIPRIX_-77",()->rejectedHold.begin());check("consultation_failed".equals(rejectedHold.phase()));check(rejectedHold.e.invites==1);fails("E_CALL_STATE",()->rejectedHold.begin());rejectedHold.e.fail=null;rejectedHold.clock.advance(30000);check("consultation_failed".equals(rejectedHold.phase()));}
    Fixture rejectedDial=new Fixture();rejectedDial.begin();rejectedDial.held(1);rejectedDial.e.fail="invite";fails("E_SIPRIX_-77",()->rejectedDial.r.continueConsultation(rejectedDial.lease,"11",REQUEST));check("returning".equals(rejectedDial.phase()));check(rejectedDial.calls().size()==1);check(rejectedDial.e.holds==2);
    Fixture rejectedMute=new Fixture();rejectedMute.begin();rejectedMute.held(1);rejectedMute.e.fail="mute";fails("E_SIPRIX_-77",()->rejectedMute.r.continueConsultation(rejectedMute.lease,"11",REQUEST));check(rejectedMute.e.ended.equals(Arrays.asList(12)));check(!"ready".equals(rejectedMute.phase()));check(rejectedMute.e.holds==1);
    Fixture rejectedUnmute=new Fixture();rejectedUnmute.dial();rejectedUnmute.e.listener.connected(12,false);rejectedUnmute.e.failUnmute=true;rejectedUnmute.e.listener.switched(12);check(Boolean.TRUE.equals(rejectedUnmute.r.snapshot(rejectedUnmute.lease).get("cleanupRequired")));check(Boolean.TRUE.equals(rejectedUnmute.calls().get(1).get("muted")));check(!"ready".equals(rejectedUnmute.phase()));
    Fixture rejectedReturn=new Fixture();rejectedReturn.ready();rejectedReturn.cancel();rejectedReturn.e.listener.terminated(12,200);rejectedReturn.e.fail="focus";rejectedReturn.held(0);check("return_failed".equals(rejectedReturn.phase()));check(Boolean.TRUE.equals(rejectedReturn.r.snapshot(rejectedReturn.lease).get("cleanupRequired")));
    Fixture rejectedDestroy=new Fixture();rejectedDestroy.ready();rejectedDestroy.e.fail="destroy";fails("E_SIPRIX_-77",()->rejectedDestroy.r.release(rejectedDestroy.lease));long cleanupLease=rejectedDestroy.r.acquire();check(rejectedDestroy.r.snapshot(cleanupLease).get("cleanupRequired").equals(true));check(((List<?>)rejectedDestroy.r.snapshot(cleanupLease).get("calls")).size()==2);rejectedDestroy.clock.advance(60000);check(rejectedDestroy.e.ends==0);fails("E_CLEANUP_REQUIRED",()->rejectedDestroy.r.initialize(cleanupLease));rejectedDestroy.e.fail=null;rejectedDestroy.r.destroy(cleanupLease);check(((List<?>)rejectedDestroy.r.snapshot(cleanupLease).get("calls")).isEmpty());
    Fixture retiredId=new Fixture();retiredId.e.listener.incoming(12,7,false,"sip:4004@example.test");retiredId.begin();retiredId.held(1);fails("E_CALL_ID_REUSED",()->retiredId.r.continueConsultation(retiredId.lease,"11",REQUEST));check(Boolean.TRUE.equals(retiredId.r.snapshot(retiredId.lease).get("cleanupRequired")));
    Fixture accountLost=new Fixture();accountLost.begin();accountLost.held(1);accountLost.e.listener.registration(7,1,"SIP/2.0 403 Forbidden");fails("E_CALL_STATE",()->accountLost.r.continueConsultation(accountLost.lease,"11",REQUEST));check(accountLost.e.invites==1);
    Fixture staleHold=new Fixture();staleHold.begin();staleHold.held(1);staleHold.e.holdState=0;fails("E_CALL_STATE",()->staleHold.r.continueConsultation(staleHold.lease,"11",REQUEST));check(staleHold.e.invites==1);
    Fixture staleTransferHold=new Fixture();staleTransferHold.ready();staleTransferHold.e.holdState=0;fails("E_CALL_STATE",()->staleTransferHold.complete());check(staleTransferHold.e.transfers==0);check(!staleTransferHold.original().containsKey("transferAttempted"));
    Fixture mutedSetup=new Fixture();mutedSetup.dial();mutedSetup.r.mute(mutedSetup.lease,"11",true);mutedSetup.e.listener.connected(12,false);mutedSetup.e.listener.switched(12);check("ready".equals(mutedSetup.phase()));check(Boolean.TRUE.equals(mutedSetup.calls().get(1).get("muted")));check(!mutedSetup.e.muted.contains(false));mutedSetup.r.mute(mutedSetup.lease,"11",false);check(Boolean.FALSE.equals(mutedSetup.original().get("muted")));check(Boolean.FALSE.equals(mutedSetup.calls().get(1).get("muted")));mutedSetup.r.mute(mutedSetup.lease,"11",true);check(Boolean.TRUE.equals(mutedSetup.calls().get(1).get("muted")));
    Fixture redirected=new Fixture();redirected.ready();redirected.e.listener.redirected(11,13);check(redirected.e.ended.equals(Arrays.asList(13)));check(redirected.calls().size()==2);check(Boolean.TRUE.equals(redirected.r.snapshot(redirected.lease).get("cleanupRequired")));redirected.e.listener.connected(13,false);check("ready".equals(redirected.phase()));
    Fixture ambiguousRedirect=new Fixture();ambiguousRedirect.ready();ambiguousRedirect.e.listener.redirected(11,12);check(ambiguousRedirect.e.ended.isEmpty());check(Boolean.TRUE.equals(ambiguousRedirect.r.snapshot(ambiguousRedirect.lease).get("cleanupRequired")));
    Fixture failedRedirect=new Fixture();failedRedirect.ready();failedRedirect.e.fail="end";failedRedirect.e.listener.redirected(11,13);check(Boolean.TRUE.equals(failedRedirect.r.snapshot(failedRedirect.lease).get("cleanupRequired")));check(failedRedirect.calls().size()==2);
    Fixture already=new Fixture();already.ready();already.cancel();already.e.listener.switched(11);already.e.listener.terminated(12,200);already.e.listener.switched(11);already.e.alreadyFocused=true;already.held(0);check("restoring_audio".equals(already.phase()));already.e.listener.switched(12);check("restoring_audio".equals(already.phase()));already.e.listener.switched(11);check("returned".equals(already.phase()));check(Boolean.FALSE.equals(already.r.snapshot(already.lease).get("cleanupRequired")));
    Fixture alreadyMissing=new Fixture();alreadyMissing.ready();alreadyMissing.cancel();alreadyMissing.e.listener.switched(11);alreadyMissing.e.listener.terminated(12,200);alreadyMissing.e.listener.switched(11);alreadyMissing.e.alreadyFocused=true;alreadyMissing.held(0);alreadyMissing.clock.advance(5000);check("return_failed".equals(alreadyMissing.phase()));check(!"returned".equals(alreadyMissing.phase()));alreadyMissing.e.listener.switched(11);check("return_failed".equals(alreadyMissing.phase()));
    Fixture alreadyNoLeg=new Fixture();alreadyNoLeg.begin();alreadyNoLeg.cancel();alreadyNoLeg.held(1);alreadyNoLeg.e.alreadyFocused=true;alreadyNoLeg.held(0);check("return_failed".equals(alreadyNoLeg.phase()));check(Boolean.TRUE.equals(alreadyNoLeg.r.snapshot(alreadyNoLeg.lease).get("cleanupRequired")));
    Fixture alreadyStale=new Fixture();alreadyStale.ready();Phone11CallRuntime.Listener staleSwitch=alreadyStale.e.listener;alreadyStale.r.destroy(alreadyStale.lease);alreadyStale.r.initialize(alreadyStale.lease);alreadyStale.r.createAccount(alreadyStale.lease,new HashMap<>());alreadyStale.r.register(alreadyStale.lease,"7",300);alreadyStale.e.listener.registration(7,0,"SIP/2.0 200 OK");alreadyStale.e.call=11;alreadyStale.r.invite(alreadyStale.lease,"7","2002");alreadyStale.e.listener.connected(11,false);alreadyStale.e.call=12;alreadyStale.e.holdState=0;alreadyStale.ready();alreadyStale.cancel();alreadyStale.e.listener.terminated(12,200);alreadyStale.e.alreadyFocused=true;alreadyStale.held(0);staleSwitch.switched(11);check("restoring_audio".equals(alreadyStale.phase()));alreadyStale.e.listener.switched(11);check("returned".equals(alreadyStale.phase()));
    Fixture alreadyConsult=new Fixture();alreadyConsult.dial();alreadyConsult.e.alreadyFocused=true;alreadyConsult.e.listener.connected(12,false);check(Boolean.TRUE.equals(alreadyConsult.r.snapshot(alreadyConsult.lease).get("cleanupRequired")));check(!"ready".equals(alreadyConsult.phase()));check(alreadyConsult.e.ended.equals(Arrays.asList(12)));
    already.e.listener.terminated(11,200);already.e.call=11;fails("E_CALL_ID_REUSED",()->already.r.invite(already.lease,"7","4004"));int staleEvents=already.events.size();already.e.listener.switched(11);check(already.events.size()==staleEvents);check(Boolean.TRUE.equals(already.r.snapshot(already.lease).get("cleanupRequired")));
    Fixture prematureHeld=new Fixture();prematureHeld.dial();prematureHeld.e.listener.held(12,0);check("dialing".equals(prematureHeld.calls().get(1).get("state")));check("calling".equals(prematureHeld.phase()));check(prematureHeld.e.focused.isEmpty());prematureHeld.e.listener.connected(12,false);prematureHeld.e.listener.switched(12);check("ready".equals(prematureHeld.phase()));
    for(String valid:Arrays.asList("+66812345678","1".repeat(32),"+"+"1".repeat(32))){Fixture international=new Fixture();international.r.beginConsultation(international.lease,"11",valid,REQUEST);check("holding".equals(international.phase()));check(international.e.holds==1);international.held(1);international.r.continueConsultation(international.lease,"11",REQUEST);check(valid.equals(international.calls().get(1).get("remoteUri")));}
    for(String invalid:Arrays.asList("66+812345678","++66812345678","+","1".repeat(33),"+"+"1".repeat(33))){Fixture invalidNumber=new Fixture();fails("E_INVALID_ARGUMENT",()->invalidNumber.r.beginConsultation(invalidNumber.lease,"11",invalid,REQUEST));check(invalidNumber.e.holds==0);check(!invalidNumber.original().containsKey("consultationAttempted"));}
    System.out.println("PASS "+assertions+" isolated Android consultation assertions; source mocks only");
  }
}
